Fix broken error message
librestfly/restfly pull request #10
Opened 2022-09-30 12:01 UTC by kalidor

Hi, i noticed some malformed error message when `UnexpectedValueError` is raised by `validate_choice_list` method in utils.py

The message seems broked from commit 6696617a6bfe19b5995d9819ce7369c39042f507, since it works before (commit cfca06a9bac0c99ad5efd86ef62931a884259faa).

Using cfca06a9bac0c99ad5efd86ef62931a884259faa:
```python
python3 /tmp/b.py                                                                                 ─╯
Traceback (most recent call last):
  File "/tmp/b.py", line 8, in <module>
    raise Exception(
Exception: name has value of obj.  Expected one of helloWorld,BAR
```

Using 6696617a6bfe19b5995d9819ce7369c39042f507 (malformed message):
```python
Traceback (most recent call last):
  File "/tmp/b.py", line 4, in <module>
    raise Exception((
Exception: helloWorldname has value of obj.  Expected one of ,BAR
```

2022-09-30 15:36 UTC, SteveMcGrath commented
Thats interesting.  Can you toss over the contents of your `b.py` file?

2022-10-01 14:41 UTC, kalidor commented
Just for info, previous output used `Exception`, since `UnexpectedValueError` is based on `Exception`...

Here are the code:
```python
from restfly.errors import UnexpectedValueError

name="name"
obj="obj"
choices = ['hello world', 'BAR']

raise UnexpectedValueError((
    f'{name} has value of {obj}.  Expected one of '
    ','.join([str(i) for i in choices])
))
```

The associated output:
```text
hello worldname has value of obj.  Expected one of ,BAR
Traceback (most recent call last):
  File "/home/gch/a.py", line 6, in <module>
    raise UnexpectedValueError((
restfly.errors.UnexpectedValueError: hello worldname has value of obj.  Expected one of ,BAR
```

2022-10-12 10:12 UTC, kalidor commented
Here is a real world example using pytenable:

```python
>> tio = TenableIO(access_key,secret_key)
>> for i in tio.workbenches.assets(('sources', 'set-has', 'INVALID CHOICE')):
>>    i
AWSfilter_value has value of az.  Expected one of ,SSMfilter_value has value of az.  Expected one of ,NESSUS_AGENTfilter_value has value of az.  Expected one of ,AZUREfilter_value has value of az.  Expected one of ,AZURE_FAfilter_value has value of az.  Expected one of ,GCPfilter_value has value of az.  Expected one of ,PVSfilter_value has value of az.  Expected one of ,NESSUS_SCANfilter_value has value of az.  Expected one of ,QUALYSfilter_value has value of az.  Expected one of ,WAS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/test//.venv/lib/python3.10/site-packages/tenable/io/workbenches.py", line 93, in assets
    query = self._workbench_query(filters, kw,
  File "/home/test//.venv/lib/python3.10/site-packages/tenable/io/workbenches.py", line 30, in _workbench_query
    query = self._parse_filters(filters, filterdefs)
  File "/home/test//.venv/lib/python3.10/site-packages/tenable/io/base/v1.py", line 58, in _parse_filters
    fval = self._check('filter_value', rval, list,
  File "/home/test//.venv/lib/python3.10/site-packages/tenable/base/endpoint.py", line 85, in _check
    return check(name=name,
  File "/home/test//.venv/lib/python3.10/site-packages/restfly/utils.py", line 546, in check
    validate_normalized(obj, validate_choice_list, kwargs.get('choices'))
  File "/home/test//.venv/lib/python3.10/site-packages/restfly/utils.py", line 472, in validate_normalized
    func(arg, item)
  File "/home/test//.venv/lib/python3.10/site-packages/restfly/utils.py", line 417, in validate_choice_list
    raise UnexpectedValueError((
restfly.errors.UnexpectedValueError: AWSfilter_value has value of az.  Expected one of ,SSMfilter_value has value of az.  Expected one of ,NESSUS_AGENTfilter_value has value of az.  Expected one of ,AZUREfilter_value has value of az.  Expected one of ,AZURE_FAfilter_value has value of az.  Expected one of ,GCPfilter_value has value of az.  Expected one of ,PVSfilter_value has value of az.  Expected one of ,NESSUS_SCANfilter_value has value of az.  Expected one of ,QUALYSfilter_value has value of az.  Expected one of ,WAS
```

2022-10-12 16:27 UTC, SteveMcGrath requested changes

2022-10-12 16:27 UTC, SteveMcGrath commented on restfly/utils.py
>                  ','.join([str(i) for i in choices])
```suggestion
                f'{name} has value of {obj}.  Expected one of '
                f'{",".join([str(i) for i in choices])}'
```

2022-10-12 16:27 UTC, SteveMcGrath commented on restfly/utils.py
>                  ','.join([str(i) for i in choices])
We want to try to avoid open concatenation when possible.

2022-10-12 18:52 UTC, SteveMcGrath commented on restfly/utils.py
>                  ','.join([str(i) for i in choices])
To confirm that it appears to now work as expected with the proposed fix: 

```python
>>> from restfly.utils import check
>>> check('test', 'test', str, choices=['a', 'b', 'c', 'd', 'e', 'f'])
test has value of test.  Expected one of a,b,c,d,e,f
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    check('test', 'test', str, choices=['a', 'b', 'c', 'd', 'e', 'f'])
  File "/Users/steve/Dropbox/Repositories/python_modules/restfly/restfly/utils.py", line 546, in check
    validate_normalized(obj, validate_choice_list, kwargs.get('choices'))
  File "/Users/steve/Dropbox/Repositories/python_modules/restfly/restfly/utils.py", line 474, in validate_normalized
    func(arg, obj)
  File "/Users/steve/Dropbox/Repositories/python_modules/restfly/restfly/utils.py", line 417, in validate_choice_list
    raise UnexpectedValueError((
restfly.errors.UnexpectedValueError: test has value of test.  Expected one of a,b,c,d,e,f
```

2022-10-12 18:55 UTC, merged